### ISSUE TITLE
Fehlender scope 'extension:read' für ATReK

### ISSUE THREAD

**Issue by gskyarts** [mittwald/contributor-support#8]
Hallo,

wie schon in Slack angesprochen hier noch mal als Issue Ticket.

Grundsätzlich geht es dadrum, dass in der OAuth Variante wir die Möglichkeit haben unsere Extension nochmal mit den entsprechenden API-Endpunkten prüfen lassen zu können. Ob die Extension überhaupt die benötigten Berechtigungen hat und auch Installiert ist. Aber mit der ATReK Variante ist dies aktuell nicht mehr möglich, da wir die entsprechenden Endpunkte nicht mehr ansprechen können, da es Berechtigungen fehlen.

Hier nochmal die Slack Nachricht:

> Hellou, könnte jemand der Cloudflare Integration (Dev) Extension den scope extension:read noch hinzufügen? Danke schon mal.
Edit: bspw. kann ich halt folgenden Endpunkt nicht aufrufen /v2/extension-instances - bekomme immer 403 PermissionDenied mit folgender message "access denied; verdict: abstain" (bearbeitet)  

Es gab auch schon folgende Antwort 

> Moinsen
die scope haben wir glaube ich noch garnicht,
Ich seh mal zu, dass wir die nachgeschoben kriegen

**Comment by patrickhilker** [comment]
> Scopes einer Extension nachträglich geändert werden

Meines Wissens ist das bisher generell gar nicht betrachtet.

Überlegung war, dass in diesem Fall der Zugriff auf die Extension für den User komplett eingeschränkt wird (und anders rum genau so), bis den neuen Scopes zugestimmt wurde. Das vermeidet beim Contributor die Komplexität, überprüfen zu müssen, welchen Scopes der Nutzer zugestimmt hat und entsprechende Sonderbehandlungen einzubauen.

Disclaimer: Möglicherweise veraltetes Wissen.

**Comment by danieldeichfuss** [comment]
Hallo zusammen, 

TLDR: brauchen wir doch nicht, scheint ein Missverständnis gewesen zu sein.

Context/Use Case: Wir benutzen ja mittwald nicht nur um mit der mittwald API zu sprechen sondern auch für Auth. Wenn wir also auf unsere eigene DB zugreifen wollen und nutzerspezifische Infos holen, checken wir bei mittwald ob der Nutzer das darf. Daher kam der Wunsch die Extension zu überprüfen, nicht zum wenn man sich den Token holt sondern auch bei bestimmten Aktionen.

Auf Freddies Empfehlung hin, machen wir das jetzt indem wir uns das jeweilige Projekt/Organisation der contextId holen, wenn das klappt dann wissen wir der Nutzer darf das.

**Comment by martin-helmich** [comment]
OK. Dann mach ich hier einfach mal zu. 😉
